ultron/stocks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('api/v1/get_history_by_stock/', views.get_history_by_stock, name='get_history_by_stock'),
    path('api/v1/get_history_by_date/', views.get_history_by_date, name='get_history_by_date'),
    path('list_strategy', views.list_strategy, name='list_strategy'),
    path('calculate', views.calculate, name='calculate'),
    path('list_khistory', views.list_khistory, name='list_khistory'),
    path('list_all_report', views.list_all_report, name='list_all_report'),
    path('stock_index', views.stock_index, name='stock_index'),
    path('', views.index, name='index')
]

ultron/ultron/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocks.urls'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ultron/stocks/models.py
from django.db import models

class Stock(models.Model):
    TYPE_CHOICES = (
        (1, '股票'),
        (2, '指数'),
        (3, '其它')
    )
    
    STATUS_CHOICES = (
        (1, '上市'),
        (0, '退市')
    )
    
    code = models.CharField(max_length=255, unique=True, blank=True, null=True, verbose_name="证券代码")
    code_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="证券名称")
    ipo_date = models.DateField(max_length=10, blank=True, null=True, verbose_name="上市日期")
    out_date = models.DateField(max_length=10, blank=True, null=True, verbose_name="退市日期")
    ipo_type = models.SmallIntegerField(
        choices=TYPE_CHOICES,
        default=1,
        verbose_name="证券类型"
    )
    ipo_status = models.SmallIntegerField(
        choices=STATUS_CHOICES,
        default=1,
        verbose_name="上市状态"
    )
    object_fund = models.TextField(blank=True, null=True, verbose_name="可操作基金")
    
    def __str__(self):
        return '%s' % (self.code_name)
    
    class Meta:
        verbose_name = "证券"
        verbose_name_plural = "所有证券"
        
class KHistory(models.Model):
    FLAG_CHOICES = (
        (1, '后复权'),
        (2, '前复权'),
        (3, '不复权')
    )
    
    STATUS_CHOICES = (
        (1, '正常交易'),
        (0, '停牌')
    )
    ST_CHOICES = (
        (1, '是'),
        (0, '否')
    )
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, verbose_name='证券名称')
    date = models.DateField(verbose_name="交易所行情日期")
    open_price = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="今开盘价格")
    high_price = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="最高价")
    low_price = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="最低价")
    close_price = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="今收盘价")
    preclose_price = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="昨日收盘价")
    volume = models.CharField(max_length=255, blank=True, null=True, verbose_name="成交数量")
    amount = models.CharField(max_length=255, blank=True, null=True, verbose_name="成交金额")
    adjust_flag = models.SmallIntegerField(
        choices=FLAG_CHOICES,
        default=1,
        verbose_name="复权状态"
    )
    turn = models.CharField(max_length=255, blank=True, null=True, verbose_name="换手率 %")
    trades_tatus = models.SmallIntegerField(
        choices=STATUS_CHOICES,
        default=1,
        verbose_name="交易状态"
    )
    pctChg = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="涨跌幅（百分比）")
    peTTM = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="滚动市盈率")
    psTTM = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="滚动市销率")
    pcfNcfTTM = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="滚动市现率")
    pbMRQ = models.DecimalField(max_digits=19, decimal_places=10, null=True, verbose_name="市净率")
    is_st = models.SmallIntegerField(
        choices=ST_CHOICES,
        default=0,
        verbose_name="是否ST"
    )
    metrics_value = models.TextField(blank=True, null=True, verbose_name="PE自动计算值")
    
    class Meta:
        verbose_name = "K线数据"
        verbose_name_plural = "所有K线数据"
        
class Strategy(models.Model):
    
    STATUS_CHOICES = (
        (2, '运算完毕'),
        (1, '运算中'),
        (0, '新创建')
    )
    
    AVAILABLE_CHOICES = (
        (1, '生效中'),
        (0, '无效')
    )
    
    TYPE_CHOICES = (
        (1, 'MM策略'),
        (2, '均值策略'),
        (3, '均值策略V1')
    )
    
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name="策略名称")
    available = models.SmallIntegerField(
        choices=AVAILABLE_CHOICES,
        default=1,
        verbose_name="是否生效"
    )
    stocks = models.ManyToManyField(Stock, related_name='strategy_stocks', verbose_name='选择策略应用于的股票/指数（可以多选）')
    s_type = models.SmallIntegerField(
        choices=TYPE_CHOICES,
        default=1,
        verbose_name="策略类型"
    )
    top_limit = models.SmallIntegerField(default=1, verbose_name="考察范围：高估上限值，单位%")
    bottom_limit = models.SmallIntegerField(default=1, verbose_name="考察范围：低估下限值，单位%")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    updated_date = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    calculated_date = models.DateTimeField(blank=True, null=True, verbose_name="运算时间")
    status = models.SmallIntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name="状态"
    )
    
    def __str__(self):
        return '%s' % (self.name)
            
    def get_high_rules_by_priority(self):   
        if self.rule_set.count():
            return self.rule_set.filter(operation=2, available=1).order_by('-priority')
                
    def get_low_rules_by_priority(self):   
        if self.rule_set.count():
            return self.rule_set.filter(operation=1, available=1).order_by('-priority')
    
    class Meta:
        verbose_name = "策略"
        verbose_name_plural = "所有策略"
        
class Rule(models.Model):
    
    OPERATION_CHOICES = (
        (2, '高估操作（卖出）'),
        (1, '低估操作（买进）')
    )
    
    STATUS_CHOICES = (
        (2, '运算完毕'),
        (1, '运算中'),
        (0, '新创建')
    )
    
    AVAILABLE_CHOICES = (
        (1, '生效中'),
        (0, '无效')
    )
    
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, verbose_name='策略名称')
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name="规则名称")
    operation = models.SmallIntegerField(
        choices=OPERATION_CHOICES,
        default=1,
        verbose_name="高估 or 低估"
    )
    limit = models.SmallIntegerField(default=1, verbose_name="高低估区间的档位，PE限值，单位%")
    holding = models.SmallIntegerField(default=1, verbose_name="股票持仓比例，单位%")
    available = models.SmallIntegerField(
        choices=AVAILABLE_CHOICES,
        default=1,
        verbose_name="是否生效"
    )
    priority = models.SmallIntegerField(default=1, verbose_name="优先级")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    updated_date = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    
    def __str__(self):
        return '%s' % (self.name)
    
    class Meta:
        verbose_name = "规则"
        verbose_name_plural = "所有规则"

ultron/stocks/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.db.models import Count, Max, Min, Avg
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.shortcuts import get_object_or_404

import json
import datetime
import requests

from datetime import date, timedelta
import json
import requests
from math import floor
import numpy as np

from django.core.management.base import BaseCommand, CommandError

from .models import Stock, KHistory, Strategy, Rule
from .serializers import json_serialize

@login_required(login_url='/admin/login/')
def index(request):
    s_list = Stock.objects.filter(ipo_type=2)
    r_list = []
    
    year = 10
    
    for s in s_list:
        kh = KHistory.objects.filter(stock=s).exclude(peTTM=0).exclude(peTTM__isnull=True).exclude(metrics_value=u'').exclude(metrics_value__isnull=True).order_by('-date')[0]
        metrics_value = json.loads(kh.metrics_value)
        pe_list = metrics_value.get("Y%s" % year)
        if pe_list and len(pe_list) > 0:
            s.h_pe = pe_list.get("h_pe_list")[-1]
            s.l_pe = pe_list.get("l_pe_list")[-1]
        s.pe_date = kh.date
        s.pe_value = kh.peTTM
        
        r_list.append(s)
        #print(metrics_value.get("Y%s" % year).get("h_pe_list"), metrics_value.get("Y%s" % year).get("l_pe_list"))
    
    template = loader.get_template('list_report.html')

    context = {
        's_list': r_list,
        'ipo_type': 2,
        'user': request.user
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/admin/login/')
def stock_index(request):
    s_list = Stock.objects.filter(ipo_type=1)
    r_list = []
    
    year = 10
    
    for s in s_list:
        kh = KHistory.objects.filter(stock=s).exclude(peTTM=0).exclude(peTTM__isnull=True).exclude(metrics_value=u'').exclude(metrics_value__isnull=True).order_by('-date')[0]
        metrics_value = json.loads(kh.metrics_value)
        pe_list = metrics_value.get("Y%s" % year)
        if pe_list and len(pe_list) > 0:
            s.h_pe = pe_list.get("h_pe_list")[-1]
            s.l_pe = pe_list.get("l_pe_list")[-1]
        s.pe_date = kh.date
        s.pe_value = kh.peTTM
        
        r_list.append(s)
        #print(metrics_value.get("Y%s" % year).get("h_pe_list"), metrics_value.get("Y%s" % year).get("l_pe_list"))
    
    template = loader.get_template('list_report.html')

    context = {
        's_list': r_list,
        'user': request.user
    }
    return HttpResponse(template.render(context, request))
    
@login_required(login_url='/admin/login/')
def list_all_report(request):
    # 股票ID
    sid = request.GET.get('sid', 1)
    # 考察年份
    year = request.GET.get('year', 10)
    
    s = Stock.objects.get(pk=sid)
    h_list = KHistory.objects.filter(stock=s).exclude(peTTM=0).exclude(peTTM__isnull=True).exclude(metrics_value=u'').exclude(metrics_value__isnull=True).order_by('-date')
    r_list = []
    
    for h in h_list:
        metrics_value = json.loads(h.metrics_value)
        pe_list = metrics_value.get("Y%s" % year)
        if pe_list and len(pe_list) > 0:
            h.h_pe = pe_list.get("h_pe_list")[-1]
            h.l_pe = pe_list.get("l_pe_list")[-1]
        h.pe_date = h.date
        h.pe_value = h.peTTM
        
        r_list.append(h)
    
    template = loader.get_template('list_all_report.html')

    context = {
        'sid': sid,
        'year': year,
        'r_list': r_list,
        'user': request.user
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/admin/login/')
def list_khistory(request):
    s_list = Stock.objects.all()
    
    template = loader.get_template('list_khistory.html')

    context = {
        's_list': s_list,
        'user': request.user
    }
    return HttpResponse(template.render(context, request))
    
@login_required(login_url='/admin/login/')
@csrf_exempt
def get_history_by_stock(request):
    sid = request.GET['sid']
    
    s = Stock.objects.get(pk=sid)
    h_list = KHistory.objects.filter(stock=s)
    
    data = []
    for h in h_list:
        data.append({
            'date': h.date,
            'open': h.open_price,
            'low': h.low_price,
            'high': h.high_price,
            'close': h.close_price,
            'pe': h.peTTM,
            'pb': h.pbMRQ,
            'volume': h.volume
        })
    
    #json_data = json_serialize(h_list, fields=('id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'preclose_price', 
    #                'volume', 'amount', 'adjust_flag', 'turn', 'trades_tatus', 'pctChg', 'peTTM', 'psTTM', 'pcfNcfTTM',
    #                'pbMRQ', 'is_st'))
    
    return JsonResponse(data, safe=False)
    
@login_required(login_url='/admin/login/')
@csrf_exempt
def get_history_by_date(request):
    data = json.loads(request.body)
    
    start_date = data.get('start_date')
    end_date = data.get('end_date')
    
    s = Stock.objects.get(pk=data.get('sid'))
    h_list = KHistory.objects.filter(date__range=[start_date, end_date], stock=s)
    
    json_data = json_serialize(h_list, fields=('id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'preclose_price', 
                    'volume', 'amount', 'adjust_flag', 'turn', 'trades_tatus', 'pctChg', 'peTTM', 'psTTM', 'pcfNcfTTM',
                    'pbMRQ', 'is_st'))  
           
    qs = KHistory.objects.filter(stock=s)         
    maxPe = qs.aggregate(Max('peTTM')).get('peTTM__max')
    minPe = qs.aggregate(Min('peTTM')).get('peTTM__min')
    maxPb = qs.aggregate(Max('pbMRQ')).get('pbMRQ__max')
    minPb = qs.aggregate(Min('pbMRQ')).get('pbMRQ__min')
                    
    #data = {
    #    'pe': [minPe, maxPe],
    #    'pb': [minPb, maxPb],
    #    'history': json_data
    #}
    
    return JsonResponse(json_data, safe=False)

@login_required(login_url='/admin/login/')
def list_strategy(request):
    my_strategies = Strategy.objects.filter(available=1)
    
    template = loader.get_template('list_strategy.html')

    context = {
        's_list': my_strategies,
        'user': request.user
    }
    return HttpResponse(template.render(context, request))    

def MaxDrawdown(return_list):
    # 1. find all of the peak of cumlative return 
    maxcum = np.zeros(len(return_list))
    b = return_list[0]
    for i in range(0,len((return_list))):
        if (return_list[i]>b):
            b = return_list[i]
        maxcum[i] = b

    # 2. then find the max drawndown point
    i = np.argmax((np.maximum.accumulate(return_list)- return_list)/np.maximum.accumulate(return_list))
    if i == 0:
        return 0,0,0
    j = np.argmax(return_list[:i])

    # 3. return the maxdrawndown
    return(return_list[j] - return_list[i]) / return_list[j],j,i

@login_required(login_url='/admin/login/')
def calculate(request):
    # 策略ID
    sid = request.GET.get('sid', 1)
    # 考察年份
    year = request.GET.get('year', 10)
    strategy = get_object_or_404(Strategy, pk=sid)
    
    str_list = []
    
    str_list.append("===========================")
    str_list.append("          策略：%s          " % strategy.name)
    str_list.append("===========================")
    
    high_rules = Rule.objects.filter(strategy=strategy, operation=2, available=1).order_by('-priority')
    low_rules = Rule.objects.filter(strategy=strategy, operation=1, available=1).order_by('-priority')

    #### 四个关注指标 ####
    # close 当日收盘价
    # peTTM 滚动市盈率

    total_stocks = 0
    total_money = 0
    total_stocks_value = 0

    today = date.today()

    #my_stocks = Stock.objects.filter(code='sh.000300')
    # 所有股票
    #my_stocks = Stock.objects.all()
    
    # 仅限选中股票
    my_stocks = strategy.stocks.all()
    
    str_list.append("股票, 日期, 低估/高估, 具体分档, P/E, Max P/E, Min P/E, 当日股价, 股持仓, 股价值, 现金, 股比例, 现金比例, 总价值")

    for s in my_stocks:
    
        # 固定成本
        cost = 10000000
        # 总起始资本
        money = 10000000
        # 持有股票数量
        s_count = 0
        # 开启交易日 2019.01.01 是周二，每周二交易
        d = date.fromisoformat("2019-01-01")
        # 总年份数
        yrs = (today-d).days/365
        # 实际交易日
        dz = date.fromisoformat("2019-01-01")
    
        # 回撤的资产list
        draw_value_list = []
        # 回撤的日期list
        draw_date_list = []
        
        # 当日收盘价
        price = 0

        
        h_list = KHistory.objects.filter(date__gte=d, trades_tatus=1, stock=s).exclude(peTTM=0).exclude(peTTM__isnull=True).exclude(metrics_value=u'').exclude(metrics_value__isnull=True)
    
        for h in h_list:
            metrics_value = json.loads(h.metrics_value)
            
            # 交易价格 @20211005 改为收盘价
            price = float(h.close_price.normalize())
        
            # 每周二之后交易
            if (h.date - d).days >= 7:
            
                # 均值策略(默认)
                max_pe = float(metrics_value.get("Y%s" % year).get("maxPE"))
                min_pe = float(metrics_value.get("Y%s" % year).get("minPE"))
                
                # MM策略
                if strategy.s_type == 2:
                    max_pe = float(metrics_value.get("Y%s" % year).get("avgMaxPE"))
                    min_pe = float(metrics_value.get("Y%s" % year).get("avgMinPE"))
                    
                pe = float(h.peTTM)
                pe_range = max_pe - min_pe
    
                top_pe = max_pe - pe_range * (strategy.top_limit/100)
                bottom_pe = min_pe + pe_range * (strategy.bottom_limit/100)
                
                # 均值策略V1
                # t 由高到低
                # b 由低到高
                if strategy.s_type == 3:
                    
                    t = metrics_value.get("Y%s" % year).get("h_pe_list")[:strategy.top_limit]
                    b = metrics_value.get("Y%s" % year).get("l_pe_list")[:strategy.bottom_limit]

ultron/stocks/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>奥创 System v1.0</title>
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/pikaday.css"/>
  <link rel="stylesheet" href="/static/css/pikaday-theme.css"/>
  <link rel="stylesheet" href="/static/css/styles.css?2"/>
  <link rel="stylesheet" href="/static/css/ion.rangeSlider.min.css"/>
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/ion.rangeSlider.min.js"></script>
  <script src="/static/js/underscore-umd-min.js"></script>
  <script src="/static/js/moment.min.js"></script>
  <script src="/static/js/moment_zh-cn.js"></script>
  <script src="/static/js/pikaday.js"></script>
  <script src="/static/js/amcharts/core.js"></script>
  <script src="/static/js/amcharts/charts.js"></script>
  <script src="/static/js/amcharts/themes/animated.js"></script>
  <script src="/static/js/amcharts/themes/frozen.js"></script>
</head>
<body>
  <!-- START NAV -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Ultron System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% url 'index' as index_url %}
            {% url 'list_strategy' as list_strategy_url %}
            {% url 'list_khistory' as list_khistory_url %}
            {% url 'stock_index' as stock_index_url %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.get_full_path == index_url %}active{% endif %}"  href="{% url 'index' %}">指数日报</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.get_full_path == stock_index_url %}active{% endif %}" href="{% url 'stock_index' %}">股票日报</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.get_full_path == list_strategy_url %}active{% endif %}" href="{% url 'list_strategy' %}">策略回测</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.get_full_path == list_khistory_url %}active{% endif %}" href="{% url 'list_khistory' %}">K线图</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">后台管理</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-1 stock-selector">
          <select id="stocks" class="form-select" onchange="calculate()">
  		{% for s in s_list %}
              <option id="{{s.id}}">{{s.code_name}}</option>
  		{% endfor %}
          </select>
      </div>
    </nav>
  </header>
  <!-- END NAV -->
  <div class="container-fluid">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

ultron/stocks/templates/calculate.html
{% extends "new_base.html" %}

{% block content %}
<div class="row content">
    <div class="row mb-3">
        <div class="col-sm-12">
            <table class="table table-hover table-striped">
              <tbody>
          		{% for s in str_list %}
                      <tr>
                          <td>
                              {{ s }}
                          </td>
                      </tr>
          		{% endfor %}
              </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

ultron/stocks/templates/list_all_report.html
{% extends "new_base.html" %}

{% block content %}
<div class="row content">
    <div class="row mb-3">
        <div class="col-sm-12">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                    <th scope="col">股指代码</th>
                    <th scope="col">股指名称</th>
                    <th scope="col">日期</th>
                    <th scope="col">PE</th>
                    <th scope="col">30%高估线</th>
                    <th scope="col">30%低估线</th>
                    {% if s.ipo_type == 2 %}
                    <th scope="col">可操作基金</th>
                    {% endif %}
                </tr>
              </thead>
              <tbody>
                  <tr>
                      <form action="{% url "list_all_report" %}" method="GET">
                          <input name="sid" value="{{ sid }}" type="hidden">
                      <td colspan="3"></td>
                      <td>
                          <select class="form-select" name="year">
                            <option selected>选择PE计算年份</option>
                            {% for i in '0123456789'|make_list %}
                                <option value="{{ forloop.counter }}" {% if year == forloop.counter|stringformat:"i" %}selected{% endif %}>{{ forloop.counter }}年</option>
                            {% endfor %}
                          </select>
                      </td>
                      <td class="text-center">
                          <input class="btn btn-info btn-sm" type="submit" value="查看">
                      </td>
                      <td colspan="3"></td>
                      </form>
                  </tr>
              {% for r in r_list %}
                  <tr>
                      <td>{{ r.stock.code }}</td>
                      <td>{{ r.stock.code_name }}</td>
                      <td>{{ r.pe_date }}</td>
                      <td>{{ r.pe_value }}<span class="badge rounded-pill {% if r.pe_value >= r.h_pe %}bg-danger{% elif r.pe_value <= r.l_pe %}bg-success{% else %}bg-light{% endif %}">{% if r.pe_value >= r.h_pe %}高{% elif r.pe_value <= r.l_pe %}低{% endif %}</span>
                      </td>
                      <td>{{ r.h_pe }}</td>
                      <td>{{ r.l_pe }}</td>
                  </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

ultron/stocks/templates/list_strategy.html
{% extends "new_base.html" %}

{% block content %}
<div class="row content">
    <div class="row mb-3">
        <div class="col-sm-12">
            {% for s in s_list %}
            <table class="table table-hover table-striped">
              <thead>
                  <tr>
                      <td colspan="8" class="text-center">
                          策略名称: {{ s.name }}-{{ s.get_s_type_display }}，高估区间 {{ s.top_limit }}%，低估区间 {{ s.bottom_limit }}%
                      </td>
                  </tr>
                  <tr>
                      <td colspan="8" class="text-center">
                          应用于股票/指数: 
                          {% for stock in s.stocks.all %}
                          [{{ stock.code }}]{{ stock.code_name }} 
                          {% endfor %}
                      </td>
                  </tr>
                <tr>
                    <th scope="col">规则名称</th>
                    <th scope="col">操作</th>
                    <th scope="col">区间档位</th>
                    <th scope="col">持仓比例</th>
                    <th scope="col">是否生效</th>
                    <th scope="col">优先级</th>
                    <th scope="col">创建时间</th>
                    <th scope="col">更新时间</th>
                </tr>
              </thead>
              <tbody>
                      {% for r in s.get_high_rules_by_priority %}
                          <tr>
                              <td>{{ r.name }}</td>
                              <td>{{ r.get_operation_display }}</td>
                              <td>{{ r.limit }}%</td>
                              <td>{{ r.holding }}%</td>
                              <td>{{ r.get_available_display }}</td>
                              <td>{{ r.priority }}</td>
                              <td>{{ r.created_date }}</td>
                              <td>{{ r.updated_date }}</td>
                          </tr>
                      {% endfor %}
                
                      {% for r in s.get_low_rules_by_priority %}
                          <tr>
                              <td>{{ r.name }}</td>
                              <td>{{ r.get_operation_display }}</td>
                              <td>{{ r.limit }}%</td>
                              <td>{{ r.holding }}%</td>
                              <td>{{ r.get_available_display }}</td>
                              <td>{{ r.priority }}</td>
                              <td>{{ r.created_date }}</td>
                              <td>{{ r.updated_date }}</td>
                          </tr>
                      {% endfor %}
                      
                      <tr>
                          <form action="{% url "calculate" %}" method="GET">
                              <input name="sid" value="{{ s.id }}" type="hidden">
                          <td colspan="3"></td>
                          <td>
                              <select class="form-select" name="year">
                                <option selected>选择PE计算年份</option>
                                <option value="1">1年</option>
                                <option value="2">2年</option>
                                <option value="3">3年</option>
                                <option value="4">4年</option>
                                <option value="5">5年</option>
                                <option value="6">6年</option>
                                <option value="7">7年</option>
                                <option value="8">8年</option>
                                <option value="9">9年</option>
                                <option value="10">10年</option>
                              </select>
                          </td>
                          <td class="text-center">
                              <input class="btn btn-info btn-sm" type="submit" value="回测">
                          </td>
                          <td colspan="3"></td>
                          </form>
                      </tr>
              </tbody>
            </table>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}